import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
  # "~/.config/alacritty/cascadia_font.toml"
  "~/.config/alacritty/berkeley_font.toml"
  # "~/.config/alacritty/jetbrains_font.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10.0
